# Generated by Django 4.0.4 on 2022-04-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.FileField(upload_to='')),
                ('imie_i_nazwisko', models.CharField(max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
