# Generated by Django 4.0.4 on 2022-05-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniaturka', models.FileField(upload_to='')),
                ('logo', models.FileField(blank=True, upload_to='')),
                ('nazwa', models.CharField(max_length=300)),
                ('grafika', models.FileField(blank=True, upload_to='')),
                ('grafika_mobilna', models.FileField(blank=True, upload_to='')),
                ('opis', models.TextField(blank=True)),
                ('grafika_fw', models.FileField(blank=True, upload_to='')),
                ('dwie_grafiki_11', models.FileField(blank=True, upload_to='')),
                ('dwie_grafiki_12', models.FileField(blank=True, upload_to='')),
                ('dwie_grafiki_21', models.FileField(blank=True, upload_to='')),
                ('grafika_mobilna_fw', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
