# Generated by Django 4.0.4 on 2022-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolio_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='dwie_grafiki_11',
            new_name='dwie_grafiki_11_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='dwie_grafiki_12',
            new_name='dwie_grafiki_12_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='dwie_grafiki_21',
            new_name='dwie_grafiki_21_1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dwie_grafiki_11_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dwie_grafiki_12_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='dwie_grafiki_21_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
