# Generated by Django 4.0.4 on 2022-05-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_portfolio_dwie_grafiki_11_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliorowtype',
            name='parent',
        ),
    ]
