# Generated by Django 4.0.4 on 2022-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_portfolio_options_portfoliovideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=300)),
                ('opis', models.TextField(max_length=400)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cena_wyswietlana', models.CharField(max_length=100)),
                ('zdjecie', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
            },
        ),
    ]
