# Generated by Django 4.0.4 on 2022-06-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
